version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'busstation'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'aidlatifaj@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'test'
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --no-input && uvicorn busstation.asgi:application --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: busstation
      DATABASE_USER: postgres
      DATABASE_PASSWORD: test
      DATABASE_PORT: 5432


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Ensure correct path and read-only mode
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - web


  celery:
    build: .
    command: celery -A busstation worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      
volumes:
  postgres_data:
  static_volume:
  media_volume:
