# Generated by Django 5.0.2 on 2024-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusLinesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='routestop',
            name='order',
            field=models.IntegerField(default=1, help_text='Order of the stop in the route'),
            preserve_default=False,
        ),
    ]
