/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        '../templates/**/*.html',
        '../../templates/**/*.html',
        '../../**/templates/**/*.html',
    ],
    darkMode: 'media',
    theme: {
        extend: {
            fontFamily: {
                body: ['Roboto', 'sans-serif'],
                slab: ['Roboto Slab', 'serif'],
                'body-light': ['Roboto:wght@300', 'sans-serif'],
                'body-bold': ['Roboto:wght@700', 'sans-serif'],
                'slab-light': ['Roboto Slab:wght@300', 'serif'],
                'slab-bold': ['Roboto Slab:wght@700', 'serif'],
              },
            screens: {
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1536px',
            },
            fontSize: {
                xs: '0.75rem',
                lg: '1.125rem',
                xl: '1.25rem',
                '2xl': '1.5rem',
                '3xl': '1.875rem',
                '4xl': '2.25rem',
                '5xl': '3rem',
                '6xl': '4rem',
            },
            colors: {
                primary: '#051976',
                'primary-dark': '#040E4A',
                'background': '#FFFFFF',
                'ring': '#051976',
                'muted-foreground': '#6B7280',
                'dark-background': '#242325', // Dark mode color
            },
            borderColor: {
                primary: '#051976',
            },
            boxShadow: {
                input: '0 0 0 2px rgba(5, 25, 118, 0.5)',
            },
            keyframes: {
                typewriter: {
                    '0%': { width: '0' },
                    '100%': { width: '100%' },
                },
                blink: {
                    '0%, 100%': { borderColor: 'transparent' },
                    '50%': { borderColor: '#051976' },
                },
            },
            animation: {
                typewriter: 'typewriter 4s steps(40, end) 1s 1 normal both',
                blink: 'blink .75s step-end infinite',
            },
            height: {
                '1': '0.25rem',
                '2': '0.5rem',
                '3': '0.75rem',
                '4': '1rem',
                '5': '1.25rem',
                '6': '1.5rem',
                '7': '1.75rem',
                '8': '2rem',
                '9': '2.25rem',
                '10': '2.5rem',
                '11': '2.75rem',
                '12': '3rem',
                '13': '3.25rem',
                '14': '3.5rem',
                '15': '3.75rem',
                '16': '4rem',
                '17': '4.25rem',
                '18': '4.5rem',
                '19': '4.75rem',
                '20': '5rem',
            },
            padding: {
                '1': '0.25rem',
                '2': '0.5rem',
                '3': '0.75rem',
                '4': '1rem',
                '5': '1.25rem',
                '6': '1.5rem',
                '7': '1.75rem',
                '8': '2rem',
                '9': '2.25rem',
                '10': '2.5rem',
                '11': '2.75rem',
                '12': '3rem',
                '13': '3.25rem',
                '14': '3.5rem',
                '15': '3.75rem',
                '16': '4rem',
                '17': '4.25rem',
                '18': '4.5rem',
                '19': '4.75rem',
                '20': '5rem',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
        require('tailwindcss-animate')
    ],
}
